# "service" is the name of this project. This will also be added to your AWS resource names.
service: email-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  region: us-east-1
plugins:
  - serverless-offline  
functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send
          method: post
          cors: true
